laravel/routes/web.php
<?php

use App\Http\Controllers\Auth\LoginUserController;
use App\Http\Controllers\Auth\RegisterUserController;
use App\Http\Controllers\Homepage\HomepageController;
use App\Http\Controllers\Newsletter\NewsletterController;
use App\Http\Controllers\Post\PostCommentsController;
use App\Http\Controllers\Post\PostController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::controller(HomepageController::class)->group(function () {
    Route::get('/', 'index')->name('homepage.index');
});

Route::controller(RegisterUserController::class)->group(function () {
    Route::get('register', 'show')->middleware('guest')->name('register.show');
    Route::post('register', 'register')->middleware('guest')->name('register');
});

Route::controller(LoginUserController::class)->group(function () {
    Route::get('login', 'show')->middleware('guest')->name('login.show');
    Route::post('login', 'login')->middleware('guest')->name('login');
    Route::post('logout', 'logout')->middleware('auth')->name('logout');
});

Route::controller(PostController::class)->middleware(['admin', 'auth'])->group(function () {
    Route::resource('post', PostController::class)->except('show');
});

Route::controller(PostController::class)->group(function () {
    Route::get('post/{post:slug}', 'show')->name('post.show');
});

Route::controller(PostCommentsController::class)->group(function () {
    Route::post('posts/{post:slug}/comments', 'store')->name('posts.comments.store');
});

Route::controller(NewsletterController::class)->group(function () {
    Route::post('email-subscription', 'createEmailSubscription')->middleware('auth')
        ->name('email-subscription.store');
});

laravel/app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Post extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected $with = ['category', 'author', 'comments'];

    /**
     * @return BelongsTo
     */
    public function author(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    /**
     * @return BelongsTo
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * @return HasMany
     */
    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class)->orderByDesc('created_at');
    }

    /**
     * @param Builder $query
     * @param array $filters
     * @return void
     */
    public function scopeFilter(Builder $query, array $filters): void
    {
        $query->when($filters['search'] ?? false,
            fn(Builder $query, string $search) => $query->where(
                fn(Builder $query) => $query->where('title', 'like', "%$search%")
                    ->orWhere('excerpt', 'like', "%$search%")
                    ->orWhere('body', 'like', "%$search%")
            ));

        $query->when($filters['category'] ?? false,
            fn(Builder $query, string $category) => $query->whereHas('category',
                fn(Builder $query) => $query->where('slug', $category)
            )
        );

        $query->when($filters['author'] ?? false,
            fn(Builder $query, string $author) => $query->whereHas('author',
                fn(Builder $query) => $query->where('username', $author)
            )
        );
    }
}

laravel/app/Http/Controllers/Post/PostCommentsController.php
<?php

namespace App\Http\Controllers\Post;

use App\Http\Controllers\Controller;
use App\Http\Requests\Post\Comment\CreateCommentRequest;
use App\Models\Post;
use Exception;

class PostCommentsController extends Controller
{
    public function store(Post $post, CreateCommentRequest $request)
    {
        try {
            $validated = $request->validated();
            $validated['user_id'] = $request->user()->id;
            $post->comments()->create($validated);
            return back();
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }
}

laravel/app/Http/Controllers/Post/PostController.php
<?php

namespace App\Http\Controllers\Post;

use App\Http\Controllers\Controller;
use App\Http\Requests\Post\StorePostRequest;
use App\Http\Requests\Post\UpdatePostRequest;
use App\Models\Category;
use App\Models\Post;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Response;
use Illuminate\Routing\Redirector;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index(): View|Factory|Application
    {
        return view('posts.index', [
            'posts' => Post::where('user_id', auth()->id())
                ->latest()
                ->with(['category', 'author'])
                ->paginate(10)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create(): Application|Factory|View
    {
        return view('posts.create', [
            'categories' => Category::all(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StorePostRequest $request
     * @return Application|RedirectResponse|Redirector
     */
    public function store(StorePostRequest $request): Application|RedirectResponse|Redirector
    {
        $validated = $request->validated();
        $validated['user_id'] = auth()->user()->id;
        $validated['thumbnail'] = $request->file('thumbnail')->store('thumbnails');
        Post::create($validated);
        return redirect('/');
    }

    /**
     * Display the specified resource.
     *
     * @param Post $post
     * @return Application|Factory|View
     */
    public function show(Post $post): View|Factory|Application
    {
        return view('posts.show', [
            'post' => $post
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Post $post
     * @return Application|Factory|View
     */
    public function edit(Post $post): Application|Factory|View
    {
        return view('posts.edit', [
            'post' => $post,
            'categories' => Category::all(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdatePostRequest $request
     * @param Post $post
     * @return Application|RedirectResponse|Redirector
     */
    public function update(UpdatePostRequest $request, Post $post): Application|RedirectResponse|Redirector
    {
        $validated = $request->validated();
        if ($request->hasFile('thumbnail')) {
            $validated['thumbnail'] = $request->file('thumbnail')->store('thumbnails');
        }
        $post->update($validated);
        return back()->with('success', 'Post updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Post $post
     * @return RedirectResponse
     */
    public function destroy(Post $post): RedirectResponse
    {
        $post->delete();
        return back()->with('success', 'Post deleted successfully');
    }
}

laravel/resources/views/posts/_comment-form.blade.php
@auth()
    <x-panel>
        <form method="POST" action="{{route('posts.comments.store', $post->slug)}}">
            @csrf
            <header class="flex items-center">
                <img src="/images/chad-logo.png" alt="" width="50" height="50"
                     class="rounded-full">
                <h3 class="font-bold ml-4">
                    Want to share your thoughts?
                </h3>
            </header>
            <div class="flex items-center mt-6">
                <label for="body"></label>
                <textarea
                    name="body"
                    id="body"
                    rows="10"
                    cols="30"
                    class="w-full text-sm border border-gray-200 rounded-xl p-2 focus:outline-none
                                             focus:ring"
                    placeholder="Leave a comment"
                    required
                ></textarea>
                <input type="hidden" name="user_id" disabled value="{{auth()->user()->id}}">
            </div>
            @error('body')
            <span class="text-red-500 text-xs italic">{{ $message }}</span>
            @enderror
            <div class="flex justify-end">
                <x-form.button>
                    Post Comment
                </x-form.button>
            </div>
        </form>
    </x-panel>
@else
    <p class="font-semibold">
        <a href="{{route('register.show')}}" class="hover:underline">
            Register
        </a>
        or
        <a href="{{route('login.show')}}" class="hover:underline">
            Login
        </a>
        to leave a comment.
    </p>
@endauth

laravel/resources/views/posts/create.blade.php
<x-layout>
    <x-setting heading="Publish New Post">
        <form method="POST" action="/post" enctype="multipart/form-data">
            @csrf
            <x-form.input name="title" required="true"/>
            <x-form.input name="slug" required="true"/>
            <x-form.input name="thumbnail" type="file" required="true"/>
            <x-form.textarea name="excerpt" required="true"/>
            <x-form.textarea name="body" required="true"/>
            <x-form.select name="category_id" :options="$categories" required="true" labelName="Category"/>
            <x-form.button>
                Publish
            </x-form.button>
        </form>
    </x-setting>
</x-layout>

laravel/resources/views/posts/edit.blade.php
<x-layout>
    <x-setting :heading="'Edit Post: ' . $post->title">
        <form method="POST" action="{{route('post.update', $post->slug)}}" enctype="multipart/form-data">
            @csrf
            @method('PATCH')
            <x-form.input name="title" required="true" :value="old('title', $post->title)"/>
            <x-form.input name="slug" required="true" :value="old('slug', $post->slug)"/>
            <div class="flex mt-6">
                <div class="flex-1">
                    <x-form.input name="thumbnail"
                                  type="file"
                                  :value="old('thumbnail', $post->thumbnail)"
                    />
                </div>
                <img src="{{asset('storage/' . $post->thumbnail)}}" alt="Thumbnail" class="rounded-xl" width="100">
            </div>
            <x-form.textarea name="excerpt" required="true">
                {{old('excerpt', $post->excerpt)}}
            </x-form.textarea>
            <x-form.textarea name="body" required="true">
                {{old('body', $post->body)}}
            </x-form.textarea>
            <x-form.select name="category_id"
                           :options="$categories"
                           required="true"
                           labelName="Category"
                           :value="old('category_id', $post->category->id)"
            />
            <x-form.button>
                Update
            </x-form.button>
        </form>
    </x-setting>
</x-layout>

laravel/resources/views/posts/index.blade.php
<x-layout>
    <x-setting heading="Manage Posts">
        <div class="flex flex-col">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                    <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                        <table class="min-w-full divide-y divide-gray-200">
                            <thead class="bg-gray-50">
                            <tr>
                                <th scope="col" class="px-6 py-3 text-left text-xs
                            font-medium text-gray-500 uppercase tracking-wider">
                                    Name
                                </th>
                                <th scope="col" class="px-6 py-3 text-left text-xs
                            font-medium text-gray-500 uppercase tracking-wider">
                                    Title
                                </th>
                                <th scope="col" class="px-6 py-3 text-left text-xs
                            font-medium text-gray-500 uppercase tracking-wider">
                                    Status
                                </th>
                                <th scope="col" class="px-6 py-3 text-left text-xs
                            font-medium text-gray-500 uppercase tracking-wider">
                                    Role
                                </th>
                                <th scope="col" class="px-6 py-3 text-left text-xs
                            font-medium text-gray-500 uppercase tracking-wider">
                                    Action
                                </th>
                            </tr>
                            <tbody class="bg-white divide-y divide-gray-200">
                            @foreach($posts as $post)
                                <tr>
                                    <td class="px-6 py-4 whitespace-nowrap">
                                        <div class="flex items-center">
                                            <div class="flex-shrink-0 h-10 w-10">
                                                <img class="h-10 w-10 rounded-full"
                                                     src="https://images.unsplash.com/photo-1516802273409-68526ee1bdd6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80"
                                                     alt=""
                                                >
                                            </div>
                                            <div class="ml-4">
                                                <div class="text-sm font-medium text-gray-900">
                                                    {{ $post->author->name }}
                                                </div>
                                                <div class="text-sm text-gray-500">
                                                    {{ $post->author->email }}
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap">
                                        <div class="text-sm text-gray-900">
                                            <a href="{{route('post.show', $post->slug)}}">
                                                {{ucwords($post->title)}}
                                            </a>
                                        </div>
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap">
                                        <span class="px-2 inline-flex text-xs leading-5
                                        font-semibold rounded-full bg-green-100 text-green-800"
                                        >
                                          Published
                                        </span>
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        @foreach($post->author->getRoleNames() as $role)
                                            {{ucwords($role)}}
                                        @endforeach
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                        <div class="flex flex-col place-items-center">
                                            <a href="{{route('post.edit', $post->slug)}}"
                                               class="text-indigo-600 hover:text-indigo-900">
                                                Edit
                                            </a>
                                            <form action="{{route('post.destroy', $post->slug)}}"
                                                  method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit"
                                                        class="text-red-600 hover:text-red-900">
                                                    Delete
                                                </button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <x-panel>
            {{ $posts->links() }}
        </x-panel>
    </x-setting>
</x-layout>

laravel/resources/views/posts/show.blade.php
<x-layout>
    <section class="px-6 py-8">
        <main class="max-w-6xl mx-auto mt-10 lg:mt-20 space-y-6">
            <article class="max-w-4xl mx-auto lg:grid lg:grid-cols-12 gap-x-10">
                <div class="col-span-4 lg:text-center lg:pt-14 mb-10">
                    <img
                        src="{{str_contains($post->thumbnail, 'http')
                                ? $post->thumbnail
                                : asset('/storage/' . $post->thumbnail)}}"
                        alt="" class="rounded-xl"
                    >
                    <p class="mt-4 block text-gray-400 text-xs">
                        Published
                        <time>{{$post->created_at->diffForHumans()}}</time>
                    </p>
                    <div class="flex items-center lg:justify-center text-sm mt-4">
                        <img src="/images/chad-logo.png" alt="Lary avatar" class="h-20 w-20">
                        <div class="ml-3 text-left">
                            <a href="/?author={{$post->author->username}}">
                                {{ $post->author->name }}
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-span-8">
                    <div class="hidden lg:flex justify-between mb-6">
                        <a href="{{route('homepage.index')}}"
                           class="transition-colors duration-300 relative inline-flex items-center text-lg hover:text-blue-500">
                            <svg width="22" height="22" viewBox="0 0 22 22" class="mr-2">
                                <g fill="none" fill-rule="evenodd">
                                    <path stroke="#000" stroke-opacity=".012" stroke-width=".5" d="M21 1v20.16H.84V1z">
                                    </path>
                                    <path class="fill-current"
                                          d="M13.854 7.224l-3.847 3.856 3.847 3.856-1.184 1.184-5.04-5.04 5.04-5.04z">
                                    </path>
                                </g>
                            </svg>
                            Back to Posts
                        </a>
                        <div class="space-x-2">
                            <x-category-button :category="$post->category"/>
                        </div>
                    </div>
                    <h1 class="font-bold text-3xl lg:text-4xl mb-10">
                        {{ $post->title }}
                    </h1>
                    <div class="space-y-4 lg:text-lg leading-loose">
                        {!!  $post->body !!}
                    </div>
                </div>
                <section class="col-span-8 col-start-5 mt-10 space-y-6">
                    @include('posts._comment-form')
                    @foreach($post->comments as $comment)
                        <x-post-comments :comment="$comment"/>
                    @endforeach
                </section>
            </article>
        </main>
    </section>
</x-layout>